name:                sweep-calculator
version:             0.1.0.0
github:              "booklearner/sweep-calculator"
license:             bsd3
author:              "booklearner"
maintainer:          "hey@booklearner.org"
copyright:           "2022 booklearner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sweep-calculator#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  sweep-calculator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sweep-calculator

tests:
  sweep-calculator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sweep-calculator
